[supervisord]
nodaemon       = true
user           =root

; -------- Program: file-server --------
[program:file-server]
command= /usr/local/bin/file-server
directory= /
autostart= true
autorestart= true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment= FILE_SERVER_DIR="/www",PORT="8000"
